
spring:
   datasource:
     url: jdbc:postgresql://localhost:5432/order
     username: java
     password: java
     driver-class-name: org.postgresql.Driver
   jpa:
     hibernate:
       ddl-auto: update
     database: postgresql
     database-platform: org.hibernate.dialect.PostgreSQLDialect
 
